### ISSUE TITLE
Bring back 'more' buttons

### ISSUE THREAD

**Issue by v15hv4** [Clubs-Council-IIITH/web#1]
Revert 36981b5e16e4505917462b260b92fde789922465

**Comment by bhavberi** [comment]
Club page more buttons added back in #9

**Comment by bhavberi** [comment]
Upcoming page buttons added in https://github.com/Clubs-Council-IIITH/web/commit/317ac98f7396c4a839980afb3ed23de90b5959dd

**Comment by bhavberi** [comment]
Account Buttons added in https://github.com/Clubs-Council-IIITH/web/commit/af38be3050a09fb6f65177c19175ce4c528b6490
