### ISSUE TITLE
404 while attempting to remove phone number from profile

### ISSUE THREAD

**Issue by How2Kritin** [Clubs-Council-IIITH/web#32]
**URL:** (my profile is currently 404'ing, so you can possibly use that to check) https://clubs.iiit.ac.in/profile/kritin.maddireddy

**Steps to reproduce:**
1. _(I cannot confirm whether this step is required or not)_ Have an account with no phone number initially.
2. Navigate to your profile, and add a phone number.
3. Save.
4. _(I cannot confirm whether this step is required or not)_ Navigate different clubs council webpages. (essentially, let your profile have the phone number for a while)
5. Go back to your profile.
6. Remove the phone number from your profile and save.

**Expected Result:**
The phone number is removed successfully, and you're still able to access your profile.

**Actual Result:**
Your profile page now shows a 404 error whenever you try to access it.

@v15hv4 @bhavberi @narenakash @The-Coder-Kishor

**Comment by bhavberi** [comment]
Hi

Thanks for finding and raising this issue. I can reproduce the issue, and I have fixed it in https://github.com/Clubs-Council-IIITH/web/commit/2be5ae87d61a8ca18b9fa281ecc3ecdcd4e14b78. You should be able to access your profile page now, and this issue fix will be deployed on the website soon.
