### ISSUE TITLE
able to add spurious members to club

### ISSUE THREAD

**Issue by cookiepresence** [Clubs-Council-IIITH/web#40]
Steps to replicate:
1. Enter an invalid email address (Example: ``spam@research.iiit.ac.in``)
2. Provide some role to the person
3. Click "Save"

Result: 
![image](https://github.com/Clubs-Council-IIITH/web/assets/127502417/af279a97-f8ef-4432-85d2-f77ec3560e36)

**Comment by bhavberi** [comment]
https://github.com/Clubs-Council-IIITH/clubs/pull/10 and https://github.com/Clubs-Council-IIITH/web/commit/a87bb373944c0569d059ff2e2af95b64f1eb77f2 will fix this issue
