### ISSUE TITLE
Extra columns in member details

### ISSUE THREAD

**Issue by gnaneswar-k** [Clubs-Council-IIITH/web#42]
When viewing a member's profile, it shows two extra empty columns after status in the table listing their roles.

![chrome_screenshot_31-Mar-2024 12_35_44 pm IST.png](https://github.com/Clubs-Council-IIITH/web/assets/97674245/c5f1400e-a27c-4eb4-ad4b-380382c6fb61)

Browser: Chrome 123.0.6312.80

OS: Android 13

Device: motorola edge 20 pro Build/T1RAS33.55-15-10-6

**Comment by bhavberi** [comment]
Thanks for reporting this issue. These columns are actually the columns for the approve and the reject buttons.

Will make changes to remove these when the buttons are not visible at all...

**Comment by bhavberi** [comment]
Fixed in 19307a6a4be9fe44b398890da261e9f39205b461
