### ISSUE TITLE
Valid youtube link not accepted by portal

### ISSUE THREAD

**Issue by ankith26** [Clubs-Council-IIITH/web#91]
## Steps to reproduce

1. Under "Manage Club/Student Body" click edit
2. Set a youtube link like: https://www.youtube.com/@OSDG-IIITH
3. Portal gives "Invalid YouTube URL" error

## Screenshot of error

![image](https://github.com/user-attachments/assets/51db28d5-c59b-421c-85b7-789010be0a0e)

**Comment by Dileepadari** [comment]
The regex is not considering this type of links, the regex have been updated, now you can try updating the link.
Hence closing the issue
